### ISSUE TITLE
how do I test this to predict for next X days?

### ISSUE THREAD

**Issue by nikhil-rss** [miguelgfierro/sciblog_support#73]
Hi,

This is really cool!!

How do I test this to get the test prediction data for next 'X' days from current date? Can you please help with the code snippet ?

**Comment by miguelgfierro** [comment]
The parameter `TIME_AHEAD` sets the number of days that you want to predict in advance. The more in the future you want to predict, the less accurate the prediction will be. The model prediction `pred_test` will have a shape of `(num_rows, TIME_AHEAD)`, having the predicted values for the next `TIME_AHEAD` days.

I updated the comments so this is clearer.
